openapi: 3.0.0
info:
  title: Stormbreaker API
  description: API for retrieving information about electric price in Finland
  version: 1.0.0
servers:
  - url: http://localhost:5001
    description: Local server
paths:
  /v1/market-price:
    post:
      summary: Get electric market price information
      description: Returns specific electric price by specifying the request body
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarketPriceReqV1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketPriceResV1'
        '400':
          description: Bad request. Error from client side. Maybe request body contains some information which is incorrect
          content: 
            application/json:
              schema:
                type: string
                example: 'start date cannot after end date'
        '500':
          description: Unexpected error from server side. Maybe fetching external encounters some problems. 
          content: 
            application/json:
              schema:
                type: string
                example: failed to fetch data
  /v1/market-price/today-tomorrow:
    get: 
      summary: Get market price for today and tomorrow (if it is available from external source)
      description: This is a quick and simple way to get market price for today and tomorrow when user does not need to care about request body. Tomorrow's price often available from 2pm-4pm everyday and it is cached in-memory with logical expiration time.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/TodayTomrrowResV1'
        '500':
          description: Unexpected error from server side. Maybe fetching data from external source encounters some problems.
components:
  schemas:
    # REQUEST SCHEMAS
    MarketPriceReqV1:
      type: object
      required:
        - starttime
        - endtime
        - margin
        - group 
        - include_vat
        - compare_to_last_year
      properties:
        starttime:
          type: string
          description: start time has to be in this format "YYYY-MM-DD"
          example: "2024-08-21"
        endtime:
          type: string
          description: end time has to be in this format "YYYY-MM-DD"
          example: "2024-08-21"
        margin:
          type: number
          format: float64
          description: Marginal is not allowed to be empty, it is ok to equal to "0"
        group:
          type: string
          description: represents 'hour', 'day', 'week', 'month', 'year'
          example: "hour"
          enum: ["hour", 'day', 'week', 'month', 'year']
        include_vat:
          type: integer
          format: int32
          description: this is legacy property that return string value and value "0" means no VAT included and string "1" is included
          enum: [0, 1]
          example: 1
        compare_to_last_year:
          type: integer
          format: int32
          enum: [0, 1]
          example: 0
    # RESPONSE SCHEMAS
    MarketPriceResV1:
      type: object
      properties:
        data:
          type: object
          properties:
            group:
              type: string
              description: represents 'hour', 'day', 'week', 'month', 'year'
              example: "hour"
              enum: ['hour', 'day', 'week', 'month', 'year']
            series:
              type: array
              description: unit and series data of electric price in targeting group
              items: 
                type: object
                properties:
                  name: 
                    type: string 
                    description: unit of electric price
                    example: 'c/kWh'
                  data: 
                    type: array
                    description: series data of electric price in targeting group
                    items: 
                      type: object 
                      properties:
                        time_utc: 
                          type: string
                          example: '2024-08-21 21:00:00'
                        orig_time:
                          type: string
                          example: '2024-08-21 00:00:00'
                        time: 
                          type: string
                          example: '2024-08-21 00:00:00'
                        price: 
                          type: number
                          format: float64
                        vat_factor: 
                          type: number
                          format: float64
                        isToday:
                          type: boolean
                          description: indicate if the searching date is today or not
                          example: false
                        includeVat: 
                          type: integer
                          enum: [0, 1]
                          example: 0
    TodayTomrrowResV1:
      type: object
      properties:
        today: 
          type: object
          properties:
            available:
              type: boolean
              example: true
            prices: 
              type: object
              description: unit and series data of electric price in targeting group
              properties:
                name: 
                  type: string 
                  description: unit of electric price
                  example: 'c/kWh'
                data: 
                  type: array
                  description: series data of electric price in targeting group
                  items: 
                    type: object 
                    properties:
                      time_utc: 
                        type: string
                        example: '2024-08-21 21:00:00'
                      orig_time:
                        type: string
                        example: '2024-08-21 00:00:00'
                      time: 
                        type: string
                        example: '2024-08-21 00:00:00'
                      price: 
                        type: number
                        format: float64
                      vat_factor: 
                        type: number
                        format: float64
                      isToday:
                        type: boolean
                        description: indicate if the searching date is today or not
                        example: true
                      includeVat: 
                        type: integer
                        enum: [0, 1]
                        example: 1
        tomorrow:
          type: object
          properties:
            available:
              type: boolean
              example: true
            prices: 
              type: object
              description: unit and series data of electric price in targeting group
              properties:
                name: 
                  type: string 
                  description: unit of electric price
                  example: 'c/kWh'
                data: 
                  type: array
                  description: series data of electric price in targeting group
                  items: 
                    type: object 
                    properties:
                      time_utc: 
                        type: string
                        example: '2024-08-21 21:00:00'
                      orig_time:
                        type: string
                        example: '2024-08-21 00:00:00'
                      time: 
                        type: string
                        example: '2024-08-21 00:00:00'
                      price: 
                        type: number
                        format: float64
                      vat_factor: 
                        type: number
                        format: float64
                      isToday:
                        type: boolean
                        description: indicate if the searching date is today or not
                        example: false
                      includeVat: 
                        type: integer
                        enum: [0, 1]
                        example: 1
