# AnhCao 2024
# This workflow will run unit test, build Docker image then tag and push to Docker registry
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Merge master branch workflow

on:
  push:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, Tag, and Push Docker Image
        run: make docker tag push


