# AnhCao 2024

name: Pull request workflow for status 'open'

on:
  pull_request:
    types: [opened]

jobs:
  build:
    name: verify on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        id: unit-tests-execution
        run: make test



